"""create knowledge assets table

Revision ID: 56ceabbb7469
Revises: c9c4054e9e52
Create Date: 2026-07-21 16:57:03.793910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ceabbb7469'
down_revision: Union[str, Sequence[str], None] = 'c9c4054e9e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_assets_content_hash'), 'knowledge_assets', ['content_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_assets_url'), 'knowledge_assets', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_assets_url'), table_name='knowledge_assets')
    op.drop_index(op.f('ix_knowledge_assets_content_hash'), table_name='knowledge_assets')
    op.drop_table('knowledge_assets')
    # ### end Alembic commands ###
