"""align organizations schema

Revision ID: 91360d58ec2f
Revises: b3801277f9e5
Create Date: 2026-08-16 21:58:46.264548

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91360d58ec2f"
down_revision: Union[str, Sequence[str], None] = "b3801277f9e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organizations",
        "website",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=2000),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("organizations_name_key"), "organizations", type_="unique")
    op.create_index(
        op.f("ix_organizations_name"), "organizations", ["name"], unique=True
    )
    op.create_unique_constraint(
        "uq_organizations_website",
        "organizations",
        ["website"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_organizations_website",
        "organizations",
        type_="unique",
    )
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.create_unique_constraint(
        op.f("organizations_name_key"),
        "organizations",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "organizations",
        "website",
        existing_type=sa.String(length=2000),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
