"""create sources table

Revision ID: b3801277f9e5
Revises: 56ceabbb7469
Create Date: 2026-08-16 19:44:06.647876

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3801277f9e5"
down_revision: Union[str, Sequence[str], None] = "56ceabbb7469"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "STANDARDS",
                "GOVERNMENT",
                "LEGAL",
                "BLOG",
                "NEWS",
                "COMMUNITY",
                "VIDEO",
                "OPEN_SOURCE",
                "DOCUMENT_ACCESSIBILITY",
                "RESEARCH",
                "VENDOR",
                name="source_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "connector_type",
            sa.Enum("RSS", "API", "SCRAPER", "MANUAL", name="connector_type"),
            nullable=False,
        ),
        sa.Column("authority_score", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("refresh_minutes", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        op.f("ix_sources_organization_id"), "sources", ["organization_id"], unique=False
    )


# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        op.f("ix_sources_organization_id"),
        table_name="sources",
    )

    op.drop_table("sources")
    # ### end Alembic commands ###
